Merges to unify code for programming testing / driver practice
DeepBlueRobotics/RobotCode2020 pull request #31
Opened 2020-03-03 04:50 UTC by alexander-mcdowell

This pull request should unify all of the branches except for climber.

2020-03-03 04:56 UTC, CoolSpy3 commented
Has your new intake code been tested?

2020-03-03 05:06 UTC, alexander-mcdowell commented
The intake code has not been tested, however, I included the intake code prior to my changes in comments in case the new code does not work.

2020-03-03 19:35 UTC, brettle approved these changes

2020-03-04 23:52 UTC, CoolSpy3 requested changes

2020-03-04 23:52 UTC, CoolSpy3 commented on src/main/java/org/team199/robot2020/commands/Shoot.java
> +        this.intake = intake;
Shouldn't this command require intake?

2020-03-06 22:28 UTC, CoolSpy3 requested changes

2020-03-06 22:28 UTC, CoolSpy3 commented on src/main/java/org/team199/lib/LinearInterpolation.java
>          }
These return calls should be switched so that ys[0] is returned when x < minX and ys[length-1] is returned when x > maxX and

2020-03-06 22:28 UTC, CoolSpy3 commented on src/main/java/org/team199/robot2020/commands/AutoShootAndDrive.java
>          addRequirements(drivetrain, intake, feeder, shooter);
This shouldn't be required because SequentialCommandGroup will automatically require all requirements of commands added to it.

2020-03-06 22:28 UTC, CoolSpy3 commented on src/main/java/org/team199/lib/LinearInterpolation.java
> +    public double maxY = -100000000;    // Give maxY an initial minimum value
These should use Double.POSITIVE_INFINITY and Double.NEGITIVE_INFINITY

2020-03-06 22:28 UTC, CoolSpy3 commented on src/main/java/org/team199/robot2020/commands/AutoShoot.java
>          addRequirements(feeder, shooter);
intake should be required

2020-03-06 23:56 UTC, CoolSpy3 approved these changes

2020-03-07 21:09 UTC, CoolSpy3 commented on src/main/java/org/team199/robot2020/commands/ShooterHorizontalAim.java
> +        limelight.setLight(true);
This should be moved to initialize()

2021-01-17 20:26 UTC, closed without merging