Shooter
DeepBlueRobotics/RobotCode2020 pull request #5
Opened 2020-01-12 00:35 UTC by SaltyJoke

2020-01-12 20:10 UTC, alexander-mcdowell commented on src/main/java/frc/robot/commands/EjectCell.java
> +public class EjectCell extends CommandBase {
What is the difference between the EjectCell command and the Shoot command? It is not entirely clear.

2020-01-16 08:36 UTC, kevinzwang requested changes

2020-01-16 08:36 UTC, kevinzwang commented on src/main/java/org/team199/robot2020/Robot.java
> +  private static Shooter shooter;
this subsystem should be in RobotContainer just like how Drivetrain is

2020-01-16 08:36 UTC, kevinzwang commented on src/main/java/org/team199/robot2020/commands/Shoot.java
> +public class Shoot extends CommandBase {
the two commands `Shoot` and `EjectCell` are confusingly named. At least add comments to their constructors!

2020-01-16 08:36 UTC, kevinzwang commented on src/main/java/org/team199/robot2020/commands/ShooterTargetSpeed.java
> +public class ShooterTargetSpeed extends CommandBase {
Why does the `Shoot` command seem to just be doing what this command should do?

2020-01-16 08:36 UTC, kevinzwang commented on src/main/java/org/team199/robot2020/subsystems/Shooter.java
> +public class Shooter implements Subsystem {
Use `extends SubsystemBase` not `implements Subsystem`.

2020-02-13 00:08 UTC, merged